### PR TITLE
Accessibility Review by Edwin and Hyder

### PR DESCRIPTION
**Pull request by egichuhis**
Hi, we have scanned my Portfolio site with the WAVE accessibility evaluation tool and the following is our report on the findings:

wave

### REPORT ✍🏽 
- Page title - no issues found
- Page language -no issues found
- Page has 1 `h1` tag - no issues found
- Page has different levels of headers - no issues found
- Page has a list - no issues found
- Page has a navigation menu
- Page has a `header` section - no issues found
- 3 Missing form labels on the contact form 
- 11 empty links in social media icons
- 21 contrast errors
- Non-descriptive alternative text

### CODE REVIEW

**Review by jerryowusu — COMMENTED** [review]
Hi @egichuhis , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

invalid


## Invalid Code Review Request

You have submitted a project that is missing some key features of the microverse readme template such as the Key Features and Future Features. Kindly make sure that all parts/sections  of the template are present and edited accordingly. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by IngDavidTM — CHANGES_REQUESTED** [review]
## Hi @egichuhis  🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!



## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [ ] Good job describing your project in the pull request :1st_place_medal:, but kindly remember that as a [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/6_accessability.md) you should create a report that includes a statement pertained to every point checked. 
  - If everything was ok, you should make a statement about that (e.g. "Page titles - no issues found").
  - If issues were found, you should link to the corresponding line of code in the Pull Request changes

- [ ] You did a good job resizing text on your project :+1:, but as you may have noticed there are some texts that disappear or get cut off, also it shouldn't overlap when you apply zoom on it because some people need to enlarge web content in order to read it. For more information about resizing you could check this [link](https://www.w3.org/WAI/test-evaluate/preliminary/#resize) :+1:

**150%**

Screenshot from 2023-01-31 06-43-04

**200%**

Screenshot from 2023-01-31 06-43-54

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by egichuhis** [comment]
I have acted on the recommendations above and hopefully, we will pass this review. 🤞🏽 
Cheers!

**Review by Favourezeugwa — APPROVED** [review]
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @egichuhis,

I am Favour 👩🏽 , your reviewer for this PR.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

happy

## Highlights 💯 
- No Linter errors ✔️
- Good commit messages ✔️
- Professional Readme file ✔️
- Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by AbayomiOlaoye — COMMENTED** [review]
Hi @egichuhis :wave, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

invalid

## Invalid Code Review Request

- You have submitted a pull request with no collaborative efforts/commits from your new coding partner as required by this milestone:
image

- Also, kindly remove the comment in the template as highlighted below to have professional and well-customized Readme file:
image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new pull request once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
